### ISSUE TITLE
[Bug] Cannot create a file when that file already exists

### ISSUE THREAD

**Issue by motiondnb** [deezer/spleeter#170] opened 2019-12-09 00:40 UTC
I am running spleeter in powershel and can do the 2 split fine using,

spleeter separate -i mytune.mp3 -o myfoldername

But when i try the 4 split using,

spleeter separate -i doishort.wav -o tingaling -p spleeter:4stems   

I get an error. I made sure tingaling was a brand new folder before running.

c:\users\ryzen lappy\appdata\local\programs\python\python37\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "c:\users\ryzen lappy\appdata\local\programs\python\python37\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "c:\users\ryzen lappy\appdata\local\programs\python\python37\lib\site-packages\spleeter\audio\ffmpeg.py", line 108, in save
    os.makedirs(directory)
  File "c:\users\ryzen lappy\appdata\local\programs\python\python37\lib\os.py", line 221, in makedirs
    mkdir(name, mode)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'tingaling\\doishort'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\RYZEN LAPPY\AppData\Local\Programs\Python\Python37\Scripts\spleeter-script.py", line 11, in <module>
    load_entry_point('spleeter==1.4.8', 'console_scripts', 'spleeter')()
  File "c:\users\ryzen lappy\appdata\local\programs\python\python37\lib\site-packages\spleeter\__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "c:\users\ryzen lappy\appdata\local\programs\python\python37\lib\site-packages\spleeter\__main__.py", line 46, in main
    entrypoint(arguments, params)
  File "c:\users\ryzen lappy\appdata\local\programs\python\python37\lib\site-packages\spleeter\commands\separate.py", line 45, in entrypoint
    separator.join()
  File "c:\users\ryzen lappy\appdata\local\programs\python\python37\lib\site-packages\spleeter\separator.py", line 68, in join
    task.get()
  File "c:\users\ryzen lappy\appdata\local\programs\python\python37\lib\multiprocessing\pool.py", line 657, in get
    raise self._value
FileExistsError: [Errno 17] Cannot create a file when that file already exists: 'tingaling\\doishort'
INFO:spleeter:File tingaling\doishort/bass.wav written
PS C:\Users\RYZEN LAPPY\Music\spleeter>

This did write the bass file ok. Its a 30 second audio file.

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                       |   Windows      |  
| Installation type | pip            |
| RAM available     | 4GB                            |
| Hardware spec     | Radeon Vega / Ryzen 3 /             |

**Comment by keliethn** [comment] 2019-12-10 00:53
Getting the same error using 2stems. Output folder permissions changed to be writable before running spleeter.

**Comment by ngoname** [comment] 2019-12-10 05:11
I get the same error as well.  I tried renaming, moving folders out and all of these things but I get the same error running PIP.  I only started doing PIP because the other method was giving me that D: drive issue.  I can run the same file many times in a row and sometimes it will give me some stems or nothing at all.

**Comment by keliethn** [comment] 2019-12-10 12:13
I tried the following:
Create the folder (I assume you are using windows), then right click and select properties. 
Under General tab, at the end there is an 'Atributes' section, usually Read-only is 'selected', just blank it and Apply/Save changes.
Then run your console As Admin and run spleeter.

This worked for me,remember to check always the Attributes section of the folder before running spleeter.

**Comment by motiondnb** [comment] 2019-12-10 18:03
Hi keliethn, yes that worked for me thanks for your help!

What I am noticing in Windows 10 is when I go to file properties, attributes, untick read only and click apply it makes the changes. If I go out of the folder and back in again windows has changed the folder back to read only. Not sure why its doing this. A quick browse shows other people have the same problem and it could be permissions related.

Is it possible for spleeter to be updated so when the folder is created the read only attribute is not ticked?

First time ive got anything off github working and first time playing with an AI algo so feeling quite chuffed right now.

**Comment by mmoussallam** [comment] 2019-12-18 14:51
Closing this because it's a duplicate of #163

**Closed by mmoussallam** 2019-12-18 14:51 UTC
Labels: bug, invalid
