### ISSUE TITLE
[Bug] Sum of output audio has missing high frequencies compared to original audio

### ISSUE THREAD

**Issue by zardini123** [deezer/spleeter#106] opened 2019-11-16 18:11 UTC
The issue I'm experiencing is that the sum of spleeter's output audio has missing high frequencies compared to original audio.  Regardless of the file input codec (and audio source), this problem seems to persist.  A full report on what frequencies the sum is missing is provided at the end of the bug report.  

I can't tell from my surface-level perspective if this is a decoding issue (ffmpeg decoding audio to a lower bitrate), or if this is inherit with the trained models.  I would expect that part of the training criteria for a AI like this, is that if the AI gets trained so that the sum of the outputs equals almost exactly the input stream.  I'd love to read the white paper to see if this condition was actually in the training criteria.

## Step to reproduce

1.  Create venv using python3
2.  Install spleeter via venv's pip3
3.  Run spleeter's executable using any model (2 through 5 stems)
4.  Spleeter outputs correct number of audio files.  Import all audio files into your favorite audio editor (Audacity, Ableton)
5.  Output sum does not contain as much high frequencies as original audio.  

## Output

Spleeter runs and reports like standard.  No issues are thrown.  Audio data is reported to load successfully.

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                |  MacOS  |
| Installation type | pip |
| RAM available     | 16 GB |
| Hardware spec     | i9 9700k,  Radeon RX 590 |

## Experimentation with the issue

After following the steps I provided above, I then imported my original file and the output spleeter audio to Ableton.  I grouped all the spleeter output audio, and inverted the group's audio.  The sum of the original audio and the inverted group reveals the audio "missing" from the spleeter audio.  Using a spectrum analyzer set to a FFT size of 16384 shows a peculiar cutoff in frequencies at 11k Hz (See image).
![Screen Shot 2019-11-16 at 12 59 50 PM](https://user-images.githubusercontent.com/7538514/68997172-75dd8580-0871-11ea-990a-3bed686a1c6b.png)
(Note: audio used here is Earth, Wind & Fire's Let's Groove, provided in the wav codec.  The y scale is in dB.  Notice the almost 72 decibel difference from the low and high shelf)
This odd case of missing frequencies above 11k Hz applies to any audio, any codec, at any sample rate I tried.  Even after resampling EWF's Let's Groove from 44.1k to 192k, the same cutoff applies.

Interestingly, sampling rate of 44.1k divided by 4 results in 11025 Hz, which is roughly 11k.  I have no idea if this gives a clue that it's a decoding issue (ffmpeg), or if its a model issue.  Though, it's interesting to think about.

**Comment by CoderSear** [comment] 2019-11-16 22:10
Able to consistently reproduce. Here's a spectrogram from Audacity of the output. 
![image](https://user-images.githubusercontent.com/6201501/68999802-c60d1580-087a-11ea-9375-d15be6478233.png)

**Comment by CoderSear** [comment] 2019-11-16 23:08
Apparently this is a duplicate of closed issues and is the intended behavior. Cutoff can be changed here: https://github.com/deezer/spleeter/wiki/5.-FAQ#why-are-there-no-high-frequencies-in-the-generated-output-files-

**Comment by zardini123** [comment] 2019-11-16 23:47
@CoderSear Interesting find!  The issue thread even has two other issues referenced referencing the same "problem."  I think it would be a good idea for the managers of the repository to put that documentation somewhere easy to find for others!

**Comment by romi1502** [comment] 2019-11-17 08:17
@zardini123, it is already documented in the [FAQ section of the wiki](https://github.com/deezer/spleeter/wiki/5.-FAQ#why-are-there-no-high-frequencies-in-the-generated-output-files-).

**Comment by zardini123** [comment] 2019-11-17 17:03
@romi1502 I believe it would be best to put a link to that specific FAQ entry in the readme.  The option to change the behavior of the mask seems very crucial for many.  I'd see many more people reporting this same "issue" I did in the future, simply because the information is not in the forefront.

**Comment by romi1502** [comment] 2019-12-27 14:24
We've just updated the [FAQ](https://github.com/deezer/spleeter/wiki/5.-FAQ#why-are-there-no-high-frequencies-in-the-generated-output-files-) to provide a new way of performing separation above 11kHz. Also configs that perform separation up to 16kHz were packaged in spleeter as mentioned in the [wiki](https://github.com/deezer/spleeter/wiki/2.-Getting-started#using-models-up-to-16khz)

**Closed by romi1502** 2019-12-27 14:24 UTC
Labels: bug, invalid
