### ISSUE TITLE
ffprobe Error

### ISSUE THREAD

**Issue by andrew-alarcon17** [deezer/spleeter#52] opened 2019-11-07 17:04 UTC
## Description

I downloaded homebrew and ffmpeg to run the code. Works fine with the audio_example given, but when I try to use another song from my library I get an ffprobe error. Also I'm putting this song in the same directory as the audio_example.mp3.

## Step to reproduce

1. Installed using 
`git clone https://github.com/Deezer/spleeter
conda env create -f spleeter/conda/spleeter-cpu.yaml
conda activate spleeter-cpu`
2. Run as `spleeter separate -i spleeter/Home.mp3 -p spleeter:2stems -o output`
3. Got 
`INFO:spleeter:Loading audio b'spleeter/Home.mp3' from 0.0 to 600.0
WARNING:spleeter:ffprobe error (see stderr output for detail)` error

## Output
The code works fine with the original audio given. This would be the output.
```INFO:spleeter:Loading audio b'spleeter/audio_example.mp3' from 0.0 to 600.0
INFO:spleeter:Audio data loaded successfully
INFO:spleeter:File output/audio_example/vocals.wav written
INFO:spleeter:File output/audio_example/accompaniment.wav written
```

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | MacOS |
| Installation type | Conda             |
| RAM available     | 4 GB                             |
| Hardware spec     |  CPU   |

**Comment by SINCd** [comment] 2019-11-07 18:52
Same Issue here

**Comment by adamxbayes** [comment] 2019-11-07 19:06
Issue for me was that I didn't have ffmpeg installed. I used homebrew to install ffmpeg and it worked a charm.

**Comment by Saiborg23** [comment] 2019-11-07 20:35
Ran `brew install ffmpeg`
Still getting `WARNING:spleeter:ffprobe error (see stderr output for detail) error`.

How do I get around this?

**Comment by mmoussallam** [comment] 2019-11-07 21:32
Hi,
It looks ike ffmpeg fails to load your audio. Unfortunately since the full stacktrace is hidden here we can't really help you. You'll need to run the command `ffprobe spleeter/Home.mp3` and see what the full error is.

**Comment by stenalpjolly** [comment] 2019-11-08 04:13
Hi

Got the same issue with docker as well 

```
docker run -v $(pwd)/output:/output spleeter:cpu separate -i audio_example_new.mp3 -o /output
INFO:spleeter:Downloading model archive https://github.com/deezer/spleeter/releases/download/v1.4.0/2stems.tar.gz
INFO:spleeter:Extracting downloaded 2stems archive
INFO:spleeter:2stems model file(s) extracted
OMP: Info #212: KMP_AFFINITY: decoding x2APIC ids.
OMP: Info #213: KMP_AFFINITY: x2APIC ids not unique - decoding legacy APIC ids.
OMP: Info #149: KMP_AFFINITY: Affinity capable, using global cpuid info
OMP: Info #154: KMP_AFFINITY: Initial OS proc set respected: 0-3
OMP: Info #156: KMP_AFFINITY: 4 available OS procs
OMP: Info #157: KMP_AFFINITY: Uniform topology
OMP: Info #159: KMP_AFFINITY: 4 packages x 1 cores/pkg x 1 threads/core (4 total cores)
OMP: Info #214: KMP_AFFINITY: OS proc to physical thread map:
OMP: Info #171: KMP_AFFINITY: OS proc 0 maps to package 0 
OMP: Info #171: KMP_AFFINITY: OS proc 1 maps to package 1 
OMP: Info #171: KMP_AFFINITY: OS proc 2 maps to package 2 
OMP: Info #171: KMP_AFFINITY: OS proc 3 maps to package 3 
OMP: Info #250: KMP_AFFINITY: pid 1 tid 1 thread 0 bound to OS proc set 0
OMP: Info #250: KMP_AFFINITY: pid 1 tid 51 thread 1 bound to OS proc set 1
INFO:spleeter:Loading audio b'audio_example_new.mp3' from 0.0 to 600.0
WARNING:spleeter:ffprobe error (see stderr output for detail)
```

**Comment by beharmon** [comment] 2019-11-08 05:36
I did an initial install of CPU version and successfully stemmed a few tracks/. Installed the GPU and abandoned it due to being on a VM. Went back to CPU and received the ffprobe error. Came here read up and in stalled via (git clone https://git.ffmpeg.org/ffmpeg.git ffmpeg )

No only did it fix the ffprobe error but I feel like the quality of the sounds of the stems vastly improved.

**Comment by stenalpjolly** [comment] 2019-11-08 06:01
Worked in Mac with 

> pip install spleeter

**Comment by phillipadsmith** [comment] 2019-11-08 18:50
I get the same error when using Docker. Haven't tried yet with Conda.

> You'll need to run the command ffprobe spleeter/Home.mp3 and see what the full error is.

If I run this, I don't get an error:

```Input #0, mp3, from '/Users/phillipadsmith/Music/Disco Fries - Family Affair (Clean Extended).mp3':
  Metadata:
    title           : Family Affair (Clean Extended)```

**Comment by SINCd** [comment] 2019-11-08 19:09
ok guys.. so I don't know if this will help anyone or not - but I was researching, installing all sorts of shit (i'm a newbie here) over and over and kept replicating the same problem that we are all having.

I installed via pip, homebrew, and everyway I could follow or find but with no results.

I did the same with ffmpeg using above methods (homebrew etc) still same result.

Then I noticed another folder called spleeter INSIDE the spleeter folder that had been created by the installs.  When I shifted my file into that folder ie.  '/User/###/spleeter/spleeter' - it worked without a hitch.  no more this ffprobe or 0-6.00 errors and the rest. It just worked.  Now, maybe this is the way it was meant to work all along, but with respect to the creators/devs, the manual does not guide newbie people who've never used command lines and such or know of the these concepts (homebrew etc).  But I did get it working and my troubles were rewarded, but still don't know if it was luck or a solution..?. hopefully, it may help or steer others and get it working for them.  I included a screenshot in hopes it may help... but I've done about 10 rips at 2 track and 5 track and its bloody worth the effort.  Thank you so much to the developers for this!  but.. can we make some sort of graphical interface or an easier streamlined process would be amazing!!

Much respect and honour to the devs/users, and i'm crossing fingers this just may work for someone.  Cheers.

![Screen Shot 2019-11-08 at 1 58 24 pm](https://user-images.githubusercontent.com/57502137/68503612-47d4c180-0231-11ea-821f-d68ad7797925.png)

**Comment by sjernigan** [comment] 2019-11-08 21:20
For Docker, you can solve this problem by reading the section that starts with 'For using your own audio file you will need to create contain...' on the Usage page of the wiki

**Comment by mmoussallam** [comment] 2019-11-08 22:30
Ok this is indeed the expected behavior.
the separation command goes:
`spleeter separate -i <path_to_audio_file> -o <path_to_audio_output_dir>` where the `path_to_audio_file` parameter must be a valid path and depends on where you are executing the command.

if your audio file `home.mp3` is in the current directory (the directory in which you are executing the command) then the right call is just `spleeter separate -i home.mp3`. The additionnal `spleeter` here in the example provided is to indicate that the audio file is located there.

**Comment by yhys07** [comment] 2019-11-09 08:14
I also had a similar issue on MacOS.
But I also failed in audio_example.mp3.
The log at the time of failure is shown below.

`% spleeter separate -i spleeter/audio_example.mp3 -p spleeter:2stems -o output
INFO:spleeter:Loading audio b'spleeter/audio_example.mp3' from 0.0 to 600.0
WARNING:spleeter:ffprobe error (see stderr output for detail)`

When I checked with `ffprobe`, I was warned that the **libiconv.2.dylib** version is out of date.


`% ffprobe spleeter/audio_example.mp3
dyld: Library not loaded: @rpath/libiconv.2.dylib
  Referenced from: /Users/XXXX/miniconda3/envs/spleeter-cpu/lib/libavformat.58.dylib
  Reason: Incompatible library version: libavformat.58.dylib requires version 9.0.0 or later, but libiconv.2.dylib provides version 7.0.0
zsh: abort      ffprobe spleeter/audio_example.mp3`


I checked with `otool`, but it looks like both the reference and version are correct.


`% otool -L /Users/XXXX/miniconda3/envs/spleeter-cpu/lib/libavformat.58.dylib
/Users/XXXX/miniconda3/envs/spleeter-cpu/lib/libavformat.58.dylib:
	@rpath/libavformat.58.dylib (compatibility version 58.0.0, current version 58.29.100)
	@rpath/libavcodec.58.dylib (compatibility version 58.0.0, current version 58.54.100)
	@rpath/libavutil.56.dylib (compatibility version 56.0.0, current version 56.31.100)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)
	@rpath/libbz2.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	@rpath/libgnutls.30.dylib (compatibility version 54.0.0, current version 54.0.0)
	@rpath/libiconv.2.dylib (compatibility version 9.0.0, current version 9.0.0)`


When I tried changing rpath to an absolute path, it worked correctly.


`% sudo install_name_tool -change "@rpath/libiconv.2.dylib" "/Users/XXXX/miniconda3/envs/spleeter-cpu/lib/libiconv.2.dylib" /Users/XXXX/miniconda3/envs/spleeter-cpu/lib/libavformat.58.dylib
`


`% spleeter separate -i spleeter/audio_example.mp3 -p spleeter:2stems -o output
INFO:spleeter:Loading audio b'spleeter/audio_example.mp3' from 0.0 to 600.0
INFO:spleeter:Audio data loaded successfully
INFO:spleeter:File output/audio_example/vocals.wav written
INFO:spleeter:File output/audio_example/accompaniment.wav written`


Another audio file was also successful.

The cause seems to be that **libavformat.58.dylib** was unable to reference **libiconv.2.dylib** correctly via rpath.

Thanks.

**Comment by kevta** [comment] 2019-11-09 16:08
I have the same issue. Running ffprobe spleeter/file.mp3 brings up no errors. I installed ffmpeg in the environment by cloning it's git repository. Didn't help. I moved the file's location to the secondary spleeter folder and made sure the path matched when specifying the input. Didn't help. Trying with the examples leads to similar issues.

**Comment by itstomas** [comment] 2019-11-11 17:19
Same here- MacOs 10.12.5, tried reinstalling ffpmeg with no avail

**Comment by johndpope** [comment] 2019-11-11 21:21
The readme needs to specify to cd into directory. It currently nests directory and file name together. This can cause above error even though ffmpeg is installed just by removing spleeter/ this error will trip up on a Mac. I do love conda / but this smart way of avoiding changing directory is causing more trouble than it’s worth.

**Comment by Ammoniya** [comment] 2019-11-12 14:51
> I get the same error when using Docker. Haven't tried yet with Conda.
> 
> > You'll need to run the command ffprobe spleeter/Home.mp3 and see what the full error is.
> 
> If I run this, I don't get an error:
> 
> ```
>   Metadata:
>     title           : Family Affair (Clean Extended)
> ```

![image](https://user-images.githubusercontent.com/20130001/68681777-ff4b3a00-0589-11ea-9d59-815f928c1edf.png)

Exactly

**Comment by Ammoniya** [comment] 2019-11-12 14:55
Run `ffprobe *.mp3` you will see the error, mostly it because Failed to read frame size: Could not seek to 65543. 

![image](https://user-images.githubusercontent.com/20130001/68681884-3ae60400-058a-11ea-9b4a-5d8a362c1271.png)

**Comment by johnny2523** [comment] 2019-11-13 14:05
I can't seem to get it to work at all i did all these steps and i still get the error
INFO:spleeter:Loading audio b'arms.mp3' from 0.0 to 600.0
WARNING:spleeter:ffprobe error (see stderr output for detail)

**Comment by pfeffigraf** [comment] 2019-11-13 14:12
I have the same issue with windows here.
First I installed ffmpeg with `git clone https://git.ffmpeg.org/ffmpeg.git` and installed spleeter with `pip install spleeter`. After creating the environment I get the samm ffprobe error:
`(spleeter-cpu) PS C:\Users\mixme> spleeter separate -i audio_example.mp3 -o audio_output
INFO:spleeter:Loading audio b'audio_example.mp3' from 0.0 to 600.0
WARNING:spleeter:ffprobe error (see stderr output for detail)`

I ran ffprobe audio_example.mp3 and don't seem to have any issues:
![spleeterffprobe](https://user-images.githubusercontent.com/57716695/68771180-c9f52980-0627-11ea-988a-b4e61c0eb423.PNG)

Any solutions? I for example don't know how to run a stderr output. I googled it but didn't find something helpful...

**Comment by johnny2523** [comment] 2019-11-13 14:23
> I have the same issue with windows here.
> First I installed ffmpeg with `git clone https://git.ffmpeg.org/ffmpeg.git` and installed spleeter with `pip install spleeter`. After creating the environment I get the same ffprobe error:
> `(spleeter-cpu) PS C:\Users\mixme> spleeter separate -i audio_example.mp3 -o audio_output INFO:spleeter:Loading audio b'audio_example.mp3' from 0.0 to 600.0 WARNING:spleeter:ffprobe error (see stderr output for detail)`
> 
> I ran ffprobe audio_example.mp3 and don't seem to have any issues:
> ![spleeterffprobe](https://user-images.githubusercontent.com/57716695/68771180-c9f52980-0627-11ea-988a-b4e61c0eb423.PNG)
> 
> Any solutions? I for example don't know how to run a stderr output. I googled it but didn't find something helpful...

I dont know how to do that either, i been trying to find that out myself.

**Comment by ravi-annaswamy** [comment] 2019-11-13 15:11
My suspicion is that the ffmpeg windows executable is not installed. (Even though python wrapper for ffmpeg is installed)

Are you able to call it from command prompt ?

If not you can look at this install instructions 
http://blog.gregzaal.com/how-to-install-ffmpeg-on-windows/

**Comment by pfeffigraf** [comment] 2019-11-13 15:48
> My suspicion is that the ffmpeg windows executable is not installed. (Even though python wrapper for ffmpeg is installed) Are you able to call it from command prompt ? If not you can look at this install instructions http://blog.gregzaal.com/how-to-install-ffmpeg-on-windows/
> […](#)
> Sent from my iPhone
> On Nov 13, 2019, at 9:23 AM, johnny2523 ***@***.***> wrote: I have the same issue with windows here. First I installed ffmpeg with git clone https://git.ffmpeg.org/ffmpeg.git and installed spleeter with pip install spleeter. After creating the environment I get the same ffprobe error: (spleeter-cpu) PS C:\Users\mixme> spleeter separate -i audio_example.mp3 -o audio_output INFO:spleeter:Loading audio b'audio_example.mp3' from 0.0 to 600.0 WARNING:spleeter:ffprobe error (see stderr output for detail) I ran ffprobe audio_example.mp3 and don't seem to have any issues: Any solutions? I for example don't know how to run a stderr output. I googled it but didn't find something helpful... I dont know how to do that either, i been trying to find that out myself. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Thank you for your quick response.
I tried this but unfortunately it didn't solve this problem. I added this path and don't get an error after running `ffmpeg -codecs`. But ffprobe error still is there.... :(

**Comment by ravi-annaswamy** [comment] 2019-11-13 16:02
Ok thanks let me also see further into this

**Comment by slanted-peter** [comment] 2019-11-13 23:27
* OS : Windows 10 x64
* "WARNING: spleeter: ffprobe error (see stderr output for detail) error"
* spleeter worked fine with "audio_example.mp3"
* problem came up when using a file of my own
* tried reducing the file's length < 600 sec and changed its bitrate to 192kpbs
* for some reason it worked, maybe pure luck, maybe not

**Comment by Faylixe** [comment] 2019-11-14 07:01
FFmpeg related error could be due to :

- FFmpeg is not found (not installed, or not in OS PATH so executable is not find).
- Your track path is not valid (meaning ffmpeg does not find your file).
- Your track could not be read by ffmpeg (corrupted, codec not supported, or whatever reason).

We can not provide assistance for every case related to FFMpeg errors unfortunately (for each environment, each track, each installation process, etc ...). What we will do although is to push a new release of _Spleeter_ soon that will output more detailed about the ffmpeg / ffprobe error so you will be able to debug the problem more easily.

Sorry for the inconvinience. In meantime you can try Google Colab, or other platforms such as `Docker` for running _Spleeter_.

**Comment by Faylixe** [comment] 2019-11-14 19:01
We will communicate soon about it but we have settled a Gitter channel @ https://gitter.im/spleeter/community.

Please consider joining the community so you can help each other more efficiently.

**Comment by mmoussallam** [comment] 2019-11-14 22:45
As stated by Felix. FFprobe errors are not directly related to spleeter. I've summarized the help we can provide in a new FAQ entry: https://github.com/deezer/spleeter/wiki/5.-FAQ#ffprobe-errors

Meanwhile I'm closing this.

**Closed by mmoussallam** 2019-11-14 22:45 UTC
Labels: bug, invalid, next release

**Comment by bespokecomponents** [comment] 2019-11-20 11:45
I was having the same problem as listed here, then I read further up about if you are already in the spleeter directory, you don't need to specify the spleeter directory where the audio file is.  So then it succesfully runs, creates the output folder with the separated 2 stems, but for me, they still BOTH play the separated file! Help!
