### ISSUE TITLE
22khz

### ISSUE THREAD

**Issue by lesecs** [deezer/spleeter#522] opened 2020-11-27 14:21 UTC
Just a quick follow up, 
I've been trying to incorporate the alternate 16kHz configuration using 
`spleeter separate -i audio_example.mp3 -o audio_output -p spleeter:4stems-16kHz`
which raises the following error:
`ERROR:spleeter:No embedded configuration 2stems-16kHz found`
And 
`spleeter separate -i my_audio_file.mp3 -c spleeter:4stems-16kHz -o /output/path`
which raises the following error:
`spleeter separate: error: argument -c/--codec: invalid choice: `

I'm currently running a Mac OSX, Python 3.7.3, I also attempted to reinstall spleeter with the same results. Any idea whats going on here? 

Thanks,

_Originally posted by @khaleelyo in https://github.com/deezer/spleeter/issues/15#issuecomment-625981182_

**Comment by lesecs** [comment] 2020-11-27 14:23
When i separate at 16 kHz, is very good but cannot separate at 22khz. Can you tell me â good cmd to do on Windows

**Comment by lesecs** [comment] 2020-11-27 14:23
When i separate at 16 kHz, is very good but cannot separate at 22khz. Can you tell me â good cmd to do on Windows

**Comment by romi1502** [comment] 2021-02-19 11:53
The error:
> spleeter separate: error: argument -c/--codec: invalid choice:

is due to the improper use of the `-c` option instead of the `-p` option.

I can't reproduce the other error:
> ERROR:spleeter:No embedded configuration 2stems-16kHz found

so I'm closing the issue.

**Closed by romi1502** 2021-02-19 11:53 UTC

**Comment by lacostenycoder** [comment] 2023-02-27 18:10
I ran into this problem but realized that by looking at the source code in the `spleeter/resources` folder there is no pre-written 22khz json files.  Comparing the default to the 16khz files, there's only one line different, which seems to be the filter cutoff frequency. So you can just make you're own edit. This example is for 2 channel split. 

The line I changed was this:
```
  "F":2048, // did simple math here double 1024 (11k default)
```
Here's my new file which I named 2stems-22khz.json 
To use it just pass in the path to your json file in the `-p` argument.

```json
{
    "train_csv": "path/to/train.csv",
    "validation_csv": "path/to/test.csv",
    "model_dir": "2stems",
    "mix_name": "mix",
    "instrument_list": ["vocals", "accompaniment"],
    "sample_rate":44100,
    "frame_length":4096,
    "frame_step":1024,
    "T":512,
    "F":2048,
    "n_channels":2,
    "separation_exponent":2,
    "mask_extension":"zeros",
    "learning_rate": 1e-4,
    "batch_size":4,
    "training_cache":"training_cache",
    "validation_cache":"validation_cache",
    "train_max_steps": 1000000,
    "throttle_secs":300,
    "random_seed":0,
    "save_checkpoints_steps":150,
    "save_summary_steps":5,
    "model":{
            "type":"unet.unet",
            "params":{}
            }
}
```
