### ISSUE TITLE
[Bug] AttributeError: module 'ffmpeg' has no attribute '_run'

### ISSUE THREAD

**Issue by MohammedMehdiTBER** [deezer/spleeter#595] opened 2021-03-11 20:05 UTC
- [x] I didn't find a similar issue already open.
- [x] I read the documentation (README AND Wiki)
- [x] I have installed FFMpeg
- [x] My problem is related to Spleeter only, not a derivative product (such as Webapplication, or GUI provided by others)

## Description

**I tried to use Spleeter on linux KDE yet still, it shows this error when I enter the following:**
`spleeter separate -p "/home/mohammedmehditber/Documents/base_config.json" -o "output_mwf" -f {filename}-{instrument}.{codec} -d 7200 -c mp3 -b 320k --mwf -B tensorflow "/media/mohammedmehditber/0E2E5DD12E5DB287/Users/Windo/Music/Muhammad Al Muqit/Anasheeds, Vol. 4/1-04 Graduation.mp3"`

## Output

```bash
spleeter separate -p "/home/mohammedmehditber/Documents/base_config.json" -o "output_mwf" -f {filename}-{instrument}.{codec} -d 7200 -c mp3 -b 320k --mwf -B tensorflow "/media/mohammedmehditber/0E2E5DD12E5DB287/Users/Windo/Music/Muhammad Al Muqit/Anasheeds, Vol. 4/1-04 Graduation.mp3"
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.8/site-packages/spleeter/audio/ffmpeg.py", line 101, in load
    probe = ffmpeg.probe(path)
AttributeError: module 'ffmpeg' has no attribute 'probe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/bin/spleeter", line 8, in <module>
    sys.exit(entrypoint())
  File "/root/anaconda3/lib/python3.8/site-packages/spleeter/__main__.py", line 256, in entrypoint
    spleeter()
  File "/root/anaconda3/lib/python3.8/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/root/anaconda3/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/root/anaconda3/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/root/anaconda3/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/anaconda3/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/anaconda3/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/root/anaconda3/lib/python3.8/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "/root/anaconda3/lib/python3.8/site-packages/spleeter/__main__.py", line 128, in separate
    separator.separate_to_file(
  File "/root/anaconda3/lib/python3.8/site-packages/spleeter/separator.py", line 376, in separate_to_file
    waveform, _ = audio_adapter.load(
  File "/root/anaconda3/lib/python3.8/site-packages/spleeter/audio/ffmpeg.py", line 102, in load
    except ffmpeg._run.Error as e:
AttributeError: module 'ffmpeg' has no attribute '_run'

```

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                |  / Linux /  |
| Installation type |  pip              |
| RAM available     | 6Go                            |
| Hardware spec     | Intel HD 3000 / Core i5 /   |
| Product Name    | Toshiba Satellite L750/L755 |

**Comment by romi1502** [comment] 2021-03-12 17:35
Hi @MohammedMehdiTBER,
I cannot reproduce your issue. The `ffmpeg` module that is imported by spleeter seems not to be the right one (as the correct one is supposed to have both a `probe` and a `_run` attribute). The right one, is the one installed by the `ffmpeg-python` package (which is a dependency of spleeter that should have been installed by `pip`).
You should check that it was correctly installed by `pip` and is not overriden by another package (installed by `pip` or `conda` or a local one).

**Comment by MohammedMehdiTBER** [comment] 2021-03-13 14:31
> ffmpeg-python

No, I have uninstalled conda. Anyway, on Windows is also showing this:
C:\Windows\system32>cd "C:\Users\Windo\Music\Spleeter"

C:\Users\Windo\Music\Spleeter>spleeter separate -p "C:\Users\Windo\Documents\base_config.json" -o "output_mwf" -f {filename}-{instrument}.{codec} -d 7200 -c mp3 -b 320k --mwf -B tensorflow "C:\Users\Windo\Music\Muhammad Al Muqit\Anasheeds, Vol. 4\1-04 Graduation.mp3"
ERROR:spleeter:ffmpeg binary not found

**Comment by romi1502** [comment] 2021-03-15 07:55
The problem, you get on Windows is a different issue that is well known:
> ERROR:spleeter:ffmpeg binary not found

is quite explicit and means that ffmpeg is not properly installed in the shell where you try to run spleeter. If you input `ffmpeg` in the same shell, you should get an error, telling the shell can't find ffmpeg.
So you need to install `ffmpeg` first as stated in the [readme](https://github.com/deezer/spleeter/blob/master/README.md). To do so, either follow the platform specific instructions from the [ffmpeg website](https://ffmpeg.org/download.html), or, if you have conda installed, use `conda install -c conda-forge ffmpeg`.
If you already installed ffmpeg, make sure the env variable are correctly set so that the path were `ffmpeg` stays is visible.

**Comment by DanielHammerin** [comment] 2021-03-31 12:07
Maybe you already solved it but I just ran `sudo pkcon install ffmpeg` in my terminal and then `pip3 install ffmpeg` in my project `venv`.
This gave me `AttributeError: module 'ffmpeg' has no attribute '_run'`
Which I found the solution to in [this](https://github.com/kkroening/ffmpeg-python/issues/174)
Solution:
> pip install ffmpeg-python
instead of
pip install ffmpeg

But wait. There's more.

> I'm guessing this happens if you've installed both, ffmpeg and ffmpeg-python.
uninstall both with:
pip uninstall ffmpeg
pip uninstall ffmpeg-python
and install ffmpeg-python again with :
pip install ffmpeg-python
This solved the problem in my system :)

Now I have a working spleeter lib in my project.

**Comment by romi1502** [comment] 2021-04-02 15:26
Ok, so to make it clear:
In order to work, spleeter needs:
- the `ffmpeg` binary. This could be installed by using a platform specific method or with conda, using `conda install ffmpeg`.
- the pypi `ffmpeg-python` package. This will be installed by default as a dependency when installing spleeter with `pip`.

The pypi `ffmpeg` package **must not** be installed.

**Closed by romi1502** 2021-04-02 15:26 UTC
Labels: bug, invalid
