### ISSUE TITLE
[Bug] Models downloaded but doesn't split the audio

### ISSUE THREAD

**Issue by Nexius03** [deezer/spleeter#171] opened 2019-12-09 08:49 UTC
## Description
Downloads the 4 stem model files but doesn't split the audio file

## Step to reproduce

Wrote "spleeter separate -i 'strokes yolo.mp3' -p spleeter:4stems -o splits" in powershell
and it downloads the 4 stems model, but it doesn't proceed to split the track

## Output

INFO:spleeter:Downloading model archive https://github.com/deezer/spleeter/releases/download/v1.4.0/4stems.tar.gz
INFO:spleeter:Validating archive checksum
INFO:spleeter:Extracting downloaded 4stems archive
INFO:spleeter:4stems model file(s) extracted

Expected output:
INFO:spleeter:File splits\strokes yolo/guitar.wav written
INFO:spleeter:File splits\strokes yolo/vocals.wav written
INFO:spleeter:File splits\strokes yolo/bass.wav written
INFO:spleeter:File splits\strokes yolo/drums.wav written

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | Windows |
| Installation type | pip             |
| RAM available     | 8GB                        |
| Hardware spec     | i5 3437U Integrated graphics  |

## Additional context
Works fine when splitting with 2 stems

**Comment by mmoussallam** [comment] 2019-12-11 13:46
Hi, have you tried removing the file (possibly corrupted during download?) and running it again ?

**Comment by mmoussallam** [comment] 2019-12-18 14:50
Closing this since I could not reproduce. Probably a download error.

**Closed by mmoussallam** 2019-12-18 14:50 UTC
Labels: bug, invalid
