### ISSUE TITLE
Please redo your installation documentations

### ISSUE THREAD

**Issue by CHJ85** [deezer/spleeter#423] opened 2020-06-15 13:51 UTC
Hi there. Please redo the installation documentations. It's all a big mess.
For starters, there is no Python and PIP anymore. Those have been removed from most distros. It's only python3 and pip3 now. And the requirements.txt file need to be updated as well. 
And please get rid of the Cobra instructions. They're just confusing and they don't work.
Took me forever to figure out what package manager that was.
And because I already have Flatpak, I really do not need yet anothert one of those.
Would be nice if you made Spleeter available on FlatHub though. At least then it wouldn't be a headache to install.

**Comment by mmoussallam** [comment] 2020-06-15 23:28
Hi @CHJ85 

Thanks a lot for these very useful comments. Sorry to read that neither the pip, the conda, nor the docker install method worked for you. Since we just love spending time keeping up with linux-only package managers, sure we'll consider flatpak, snap, appimage, ... you name it!

I'm closing this but don't worry, we keep a copy in a very special internal board dedicated to the most constructive contributions received.

Best regards,

**Closed by mmoussallam** 2020-06-15 23:28 UTC
Labels: question

**Comment by CHJ85** [comment] 2020-06-15 23:49
No need to be so snarky and sarcastic.
I'm just trying to help.
Python 2.7's PIP package was dropped and Python 3 was upgraded to 3.8 in the main repositories (at least Ubuntu, Pop OS and Linux Mint). Conda did not work. Not the version from their website nor the PyPI version.
So a sandboxed Flatpak would solve this. Of course that means an additional version of Python on your system, but at least it's gonna work.

**Comment by mmoussallam** [comment] 2020-06-17 14:25
Hi @CHJ85 

Let me just rephrase my answer in a clearer way. Since *spleeter* is based on tensorflow1 , we cannot yet release a python3.8 compatible version. We are quite aware of this and made it clear from the [Readme](../Readme.md) and the [Documentation Wiki](https://github.com/deezer/spleeter/wiki/5.-FAQ#python-38). Working on a TF2 port is our long-term solution but also quite time-consuming.

To run *spleeter* you will then need a sandboxed python3.6 or 3.7 on your system. We provide many solutions for that through:
* `pip` (yes you'll have to run it in a 3.6/3/7 virtualenv if your systems' python is 3.8)
* `Conda` which remains the recommended way to install *spleeter*. It has some drawbacks but at least it is a **cross-platform** solution that is widely adopted by researchers and developers
* and `Docker` images pre-built and ready to deploy and use

I'm genuinely sorry if you did not manage to have any of these working, and you can always **constructively** open an issue ticket reporting what the problem is and we will help you solve it.

We have no plan to add support for platform-specific package managers. Maintaining the current solution is already a challenge. However there may be some [community members](https://gitter.im/spleeter/community) interested in this.
