### ISSUE TITLE
[Bug] IndexError: index 1 is out of bounds for axis 1 with size 1

### ISSUE THREAD

**Issue by DGideas** [deezer/spleeter#303] opened 2020-03-26 05:21 UTC
## Description

When I use ```spleeter separate``` a audio file, I met this error:
```prompt
Traceback (most recent call last):
  File "/usr/local/bin/spleeter", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.6/dist-packages/spleeter/__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "/usr/local/lib/python3.6/dist-packages/spleeter/__main__.py", line 46, in main
    entrypoint(arguments, params)
  File "/usr/local/lib/python3.6/dist-packages/spleeter/commands/separate.py", line 45, in entrypoint
    synchronous=False
  File "/usr/local/lib/python3.6/dist-packages/spleeter/separator.py", line 191, in separate_to_file
    sources = self.separate(waveform, audio_descriptor)
  File "/usr/local/lib/python3.6/dist-packages/spleeter/separator.py", line 157, in separate
    return self.separate_librosa(waveform, audio_descriptor)
  File "/usr/local/lib/python3.6/dist-packages/spleeter/separator.py", line 145, in separate_librosa
    stft = self.stft(waveform)
  File "/usr/local/lib/python3.6/dist-packages/spleeter/separator.py", line 126, in stft
    dl, dr = (data[:, :, 0].T, data[:, :, 1].T) if inverse else (data[:, 0], data[:, 1])
IndexError: index 1 is out of bounds for axis 1 with size 1
```

## Step to reproduce

1. Installed using `pip install spleeter`(spleeter-1.5.0)
2. Run as `spleeter separate -i 68481579482858.mp3 -o output/` (On Colab environment)
Attach: [68481579482858.zip](https://github.com/deezer/spleeter/files/4385132/68481579482858.zip)

3. Got this error

## Output

```bash
Share what your terminal says when you run the script (as well as what you would expect).
```

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | Ubuntu 18.04 |
| Installation type | pip  |
| RAM available     | 12GB                             |
| Hardware spec     | CPU           |

**Comment by alreadytaikeune** [comment] 2020-03-26 13:37
Hi @DGideas it seems like you are using mono-channel audio, whereas the network expects stereo. For now a quick fix might be to transform your file to stereo. We can also work on supporting mono on our end.

**Comment by romi1502** [comment] 2020-03-27 09:11
Hi @DGideas, the issue is due to the new STFT backend based on librosa that was just introduced in version 1.5. The new backend does not support files that are not stereo. We will push a fix soon.
In the meantime, you can use the tensorflow STFT backend that still works with mono files:
```python
spleeter separate -i <mono_audiofile> -B tensorflow
```
Note that it will return stereo file.

**Comment by alreadytaikeune** [comment] 2020-03-27 10:17
Hi @DGideas it was indeed an error that was specific to the librosa stft computation. I included a fix in a new PR https://github.com/deezer/spleeter/pull/305. You can try this it should fix your issue.

**Comment by mmoussallam** [comment] 2020-04-05 11:59
Hi @DGideas 

The PR has now been merged. Your issue shoud be fixed, but let us know if  otherwise.

**Closed by mmoussallam** 2020-04-05 11:59 UTC
Labels: bug, invalid

**Comment by DGideas** [comment] 2020-04-13 09:32
@mmoussallam @alreadytaikeune 
I tested this file with the latest master branch code and it works! Thanks you for your PR :)

This problem should be fixed.
